### ISSUE TITLE
top crashes with index out of range

### ISSUE THREAD

**Issue by ahmetb** [sachin-jayant-joshi/docker#3]
top from container (script output) http://cl.ly/2W2G1n3M3D2T

![](http://cl.ly/image/2j360R1Y1Y2O/Image%202015-02-04%20at%202.22.13%20PM.png)

```
top - 22:21:31 up 13 days, 11:32,  0 users,  load average: 0.20, 0.18, 0.25
Tasks:   2 total,   1 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.4 sy,  0.0 ni, 97.8 id,  1.6 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   3524956 total,  2073704 used,  1451252 free,    99576 buffers
KiB Swap:        0 total,        0 used,        0 free.  1657828 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
time error: index out of range

goroutine 12 [running]:
github.com/docker/docker/pkg/term.writeConsoleOutput(0x1c, 0xabb3f0, 0x0, 0x0, 0x3d00d2, 0xc0820c4960, 0x5b94d4, 0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/pkg/term/console_windows.go:296 +0x22f
github.com/docker/docker/pkg/term.clearDisplayRect(0x1c, 0x600d2000fdb20, 0x3d00d2000600d1, 0x5c02e6, 0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/pkg/term/console_windows.go:368 +0x1f8
github.com/docker/docker/pkg/term.clearDisplayRange(0x1c, 0x600d2000f0020, 0x3d00d2000600d1, 0x0, 0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/pkg/term/console_windows.go:382 +0xbc
github.com/docker/docker/pkg/term.(*WindowsTerminal).HandleOutputCommand(0xc082089dd0, 0xc082072000, 0x3, 0x100, 0x0, 0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/pkg/term/console_windows.go:769 +0x144d
github.com/docker/docker/pkg/term.(*terminalWriter).Write(0xc082078b80, 0xc082098000, 0x78e, 0x1000, 0xf, 0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/pkg/term/term_emulator.go:105 +0x375
bufio.(*Reader).writeBuf(0xc082012a20, 0x2c3af0, 0xc082078b80, 0xf, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:463 +0xac
bufio.(*Reader).WriteTo(0xc082012a20, 0x2c3af0, 0xc082078b80, 0x72, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:444 +0x230
io.Copy(0x2c3af0, 0xc082078b80, 0x2c3960, 0xc082012a20, 0x0, 0x0, 0x0)
        c:/go/src/io/io.go:354 +0xb9
github.com/docker/docker/api/client.func┬╖023(0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/api/client/hijack.go:211 +0x1ed
github.com/docker/docker/pkg/promise.func┬╖001()
        c:/gopath/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x36
created by github.com/docker/docker/pkg/promise.Go
        c:/gopath/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x102

goroutine 1 [chan receive, 17 minutes]:
github.com/docker/docker/api/client.(*DockerCli).CmdRun(0xc08206c780, 0xc08200c160, 0x3, 0x3, 0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/api/client/commands.go:2352 +0xe56
reflect.callMethod(0xc082088cf0, 0xc0820d9be0)
        c:/go/src/reflect/value.go:605 +0x180
reflect.methodValueCall(0xc08200c160, 0x3, 0x3, 0x1, 0xc082088cf0, 0xc08206c801, 0xc082058240, 0x4, 0xc082046008, 0x1, ...)
        c:/go/src/reflect/asm_amd64.s:29 +0x3d
github.com/docker/docker/api/client.(*DockerCli).Cmd(0xc08206c780, 0xc08200c150, 0x4, 0x4, 0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/api/client/cli.go:80 +0x385
main.main()
        c:/gopath/src/github.com/docker/docker/docker/docker.go:128 +0xb68
```

**Comment by sachin-jayant-joshi** [comment]
This is happening because can't marshal 0 sized array.

**Comment by sachin-jayant-joshi** [comment]
Fixed in latest drop
Please reopen if repros.
