### ISSUE TITLE
still panics

### ISSUE THREAD

**Issue by ahmetb** [sachin-jayant-joshi/docker#9]
I can easily get it crashing consistently. we must fix this before the release. @sachin-jayant-joshi can you please prioritize? binary built from your PR branch.

Your `\amd64\2_5_15\docker.exe` private drop works just fine.

```
c:\gopath\src\github.com\docker\docker\junk>..\docker\docker.exe run -it ubuntu bash
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0x10100000001 pc=0x42853b]

goroutine 28 [running]:
runtime.throw(0xab2740)
        c:/go/src/pkg/runtime/panic.c:520 +0x7e fp=0x32f9c0 sp=0x32f9a8
runtime.sigpanic()
        c:/go/src/pkg/runtime/os_windows.c:352 +0x4b fp=0x32f9d8 sp=0x32f9c0
runtime.mallocgc(0x2, 0x74cfa0, 0x1)
        c:/go/src/pkg/runtime/malloc.goc:127 +0x50b fp=0x32fa40 sp=0x32f9d8
runtime.new(0x74cfa0, 0x0)
        c:/go/src/pkg/runtime/malloc.goc:826 +0x3b fp=0x32fa60 sp=0x32fa40
github.com/docker/docker/pkg/term.getNumberOfConsoleInputEvents(0x18, 0x0, 0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/pkg/term/console_windows.go:518 +0x45 fp=0x32fae0 sp=0x32fa60
github.com/docker/docker/pkg/term.getAvailableInputEvents(0x0, 0x0, 0x0, 0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/pkg/term/console_windows.go:1024 +0xbb fp=0x32fb68 sp=0x32fae0
github.com/docker/docker/pkg/term.(*WindowsTerminal).ReadChars(0xc08200b1d0, 0x2d22d8, 0xc08203a000, 0xc08209c000, 0x8000, 0x8000, 0x73b660, 0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/pkg/term/console_windows.go:1060 +0x70 fp=0x32fc08 sp=0x32fb68
github.com/docker/docker/pkg/term.(*terminalReader).Read(0xc08208c5c0, 0xc08209c000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/pkg/term/term_emulator.go:146 +0x110 fp=0x32fc68 sp=0x32fc08
io.Copy(0x2d2288, 0xc08208e5f0, 0x2d2210, 0xc08208c5c0, 0x0, 0x0, 0x0)
        c:/go/src/pkg/io/io.go:353 +0x1fa fp=0x32fd30 sp=0x32fc68
net.genericReadFrom(0x2d1e78, 0xc08203a088, 0x2d2210, 0xc08208c5c0, 0x0, 0x0, 0x0)
        c:/go/src/pkg/net/net.go:405 +0xba fp=0x32fd80 sp=0x32fd30
net.(*TCPConn).ReadFrom(0xc08203a088, 0x2d2210, 0xc08208c5c0, 0x2d2260, 0x0, 0x0)
        c:/go/src/pkg/net/tcpsock_posix.go:72 +0xef fp=0x32fdf0 sp=0x32fd80
io.Copy(0x2d1e78, 0xc08203a088, 0x2d2210, 0xc08208c5c0, 0x0, 0x0, 0x0)
        c:/go/src/pkg/io/io.go:349 +0x144 fp=0x32feb8 sp=0x32fdf0
github.com/docker/docker/api/client.func┬╖024(0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/api/client/hijack.go:221 +0xdc fp=0x32ff70 sp=0x32feb8
github.com/docker/docker/pkg/promise.func┬╖001()
        c:/gopath/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x35 fp=0x32ffa8 sp=0x32ff70
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445 fp=0x32ffb0 sp=0x32ffa8
created by github.com/docker/docker/pkg/promise.Go
        c:/gopath/src/github.com/docker/docker/pkg/promise/promise.go:9 +0xae

goroutine 16 [select]:
net/http.(*persistConn).roundTrip(0xc08202a2c0, 0xc08208e5c0, 0x0, 0x0, 0x0)
        c:/go/src/pkg/net/http/transport.go:1015 +0x6e2
net/http.(*Transport).RoundTrip(0xc08204e180, 0xc0820228f0, 0xd8, 0x0, 0x0)
        c:/go/src/pkg/net/http/transport.go:208 +0x4a1
net/http.send(0xc0820228f0, 0x2d0638, 0xc08204e180, 0xc0820900e0, 0x0, 0x0)
        c:/go/src/pkg/net/http/client.go:195 +0x444
net/http.(*Client).send(0xc082065290, 0xc0820228f0, 0x6d, 0x0, 0x0)
        c:/go/src/pkg/net/http/client.go:118 +0x162
net/http.(*Client).doFollowingRedirects(0xc082065290, 0xc0820228f0, 0x9473d0, 0x0, 0x0, 0x0)
        c:/go/src/pkg/net/http/client.go:343 +0x986
net/http.(*Client).Do(0xc082065290, 0xc0820228f0, 0xc, 0x0, 0x0)
        c:/go/src/pkg/net/http/client.go:153 +0x19a
github.com/docker/docker/api/client.(*DockerCli).call(0xc0820288c0, 0x86c250, 0x4, 0xc082014600, 0x52, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        c:/gopath/src/github.com/docker/docker/api/client/utils.go:94 +0x754
github.com/docker/docker/api/client.(*DockerCli).CmdRun(0xc0820288c0, 0xc08200a340, 0x3, 0x3, 0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/api/client/commands.go:2348 +0xb86
reflect.callMethod(0xc082064ab0, 0xc0820bbbf8)
        c:/go/src/pkg/reflect/value.go:761 +0x192
reflect.methodValueCall(0xc08200a340, 0x3, 0x3, 0x1, 0xc082064ab0)
        c:/go/src/pkg/reflect/asm_amd64.s:26 +0x2b
github.com/docker/docker/api/client.(*DockerCli).Cmd(0xc0820288c0, 0xc08200a330, 0x4, 0x4, 0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/api/client/cli.go:81 +0x31a
main.main()
        c:/gopath/src/github.com/docker/docker/docker/docker.go:133 +0xa5e

goroutine 19 [finalizer wait]:
runtime.park(0x418e40, 0xab77b0, 0xab58c9)
        c:/go/src/pkg/runtime/proc.c:1369 +0xac
runtime.parkunlock(0xab77b0, 0xab58c9)
        c:/go/src/pkg/runtime/proc.c:1385 +0x42
runfinq()
        c:/go/src/pkg/runtime/mgc0.c:2644 +0xdd
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
        c:/go/src/pkg/os/signal/signal_unix.go:21 +0x25
created by os/signal.init┬╖1
        c:/go/src/pkg/os/signal/signal_unix.go:27 +0x39

goroutine 26 [chan receive]:
github.com/docker/docker/api/client.(*DockerCli).hijack(0xc0820288c0, 0x86c250, 0x4, 0xc08204e000, 0x76, 0x1, 0x2d0a40, 0xc08208c5c0, 0x2d0a18, 0xc08208c540, ...)
        c:/gopath/src/github.com/docker/docker/api/client/hijack.go:237 +0xbec
github.com/docker/docker/api/client.func┬╖014(0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/api/client/commands.go:2326 +0x1f8
github.com/docker/docker/pkg/promise.func┬╖001()
        c:/gopath/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x35
created by github.com/docker/docker/pkg/promise.Go
        c:/gopath/src/github.com/docker/docker/pkg/promise/promise.go:9 +0xae

goroutine 24 [IO wait]:
net.runtime_pollWait(0x2d1d78, 0x72, 0x0)
        c:/go/src/pkg/runtime/netpoll.goc:146 +0x6d
net.(*pollDesc).Wait(0xc0820942f0, 0x72, 0x0, 0x0)
        c:/go/src/pkg/net/fd_poll_runtime.go:84 +0x4d
net.(*ioSrv).ExecIO(0xc08203a2d0, 0xc0820941e0, 0x86e990, 0x7, 0x9472d8, 0xc082014900, 0x0, 0x0)
        c:/go/src/pkg/net/fd_windows.go:188 +0x242
net.(*netFD).Read(0xc082094180, 0xc082099000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/pkg/net/fd_windows.go:458 +0x156
net.(*conn).Read(0xc08203a2e0, 0xc082099000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/pkg/net/net.go:122 +0xee
net/http.noteEOFReader.Read(0x2d1e28, 0xc08203a2e0, 0xc08202a318, 0xc082099000, 0x1000, 0x1000, 0xacad40, 0x0, 0x0)
        c:/go/src/pkg/net/http/transport.go:1203 +0x79
net/http.(*noteEOFReader).Read(0xc0820bc760, 0xc082099000, 0x1000, 0x1000, 0xc082058680, 0x0, 0x0)
        <autogenerated>:124 +0xd1
bufio.(*Reader).fill(0xc082014900)
        c:/go/src/pkg/bufio/bufio.go:97 +0x1ba
bufio.(*Reader).Peek(0xc082014900, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/pkg/bufio/bufio.go:132 +0x108
net/http.(*persistConn).readLoop(0xc08202a2c0)
        c:/go/src/pkg/net/http/transport.go:782 +0x9c
created by net/http.(*Transport).dialConn
        c:/go/src/pkg/net/http/transport.go:600 +0x946

goroutine 25 [runnable]:
net/http.(*persistConn).writeLoop(0xc08202a2c0)
        c:/go/src/pkg/net/http/transport.go:885 +0x396
created by net/http.(*Transport).dialConn
        c:/go/src/pkg/net/http/transport.go:601 +0x95e

goroutine 27 [IO wait]:
net.runtime_pollWait(0x2d1cc8, 0x72, 0x0)
        c:/go/src/pkg/runtime/netpoll.goc:146 +0x6d
net.(*pollDesc).Wait(0xc082094470, 0x72, 0x0, 0x0)
        c:/go/src/pkg/net/fd_poll_runtime.go:84 +0x4d
net.(*ioSrv).ExecIO(0xc08203a2d0, 0xc082094360, 0x86e990, 0x7, 0x9472d8, 0x0, 0x0, 0x0)
        c:/go/src/pkg/net/fd_windows.go:188 +0x242
net.(*netFD).Read(0xc082094300, 0xc0820c3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/pkg/net/fd_windows.go:458 +0x156
net.(*conn).Read(0xc08203a088, 0xc0820c3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/pkg/net/net.go:122 +0xee
bufio.(*Reader).fill(0xc082014540)
        c:/go/src/pkg/bufio/bufio.go:97 +0x1ba
bufio.(*Reader).WriteTo(0xc082014540, 0x2d0a18, 0xc08208c540, 0x0, 0x0, 0x0)
        c:/go/src/pkg/bufio/bufio.go:441 +0x203
io.Copy(0x2d0a18, 0xc08208c540, 0x2d2068, 0xc082014540, 0x0, 0x0, 0x0)
        c:/go/src/pkg/io/io.go:345 +0xbb
github.com/docker/docker/api/client.func┬╖023(0x0, 0x0)
        c:/gopath/src/github.com/docker/docker/api/client/hijack.go:210 +0x136
github.com/docker/docker/pkg/promise.func┬╖001()
        c:/gopath/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x35
created by github.com/docker/docker/pkg/promise.Go
        c:/gopath/src/github.com/docker/docker/pkg/promise/promise.go:9 +0xae

c:\gopath\src\github.com\docker\docker\junk>
```

**Comment by sachin-jayant-joshi** [comment]
Fixed in latest drop
Please reopen if repros.
